language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev" # 3.7 development branch
install:
  - pip install -r python/dev-requirements.txt
script:
  - pytest ./python/tests/
